### ISSUE TITLE
Unable to run qauld docker container

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#559]
running command:
`docker run --detach --publish 9229:9229 --volume /home/user/containers/qaul/config:/srv/qaul qaulnet/qauld:v2.0.0-beta.15`

container log:
```
running libqaul 2.0.0-beta.15
failed to creating version file path: /srv/qaul/version
upgrade to new version failed
```
also getting same error for this docker-compose:
```
version: "2"
services:
  app:
    image: qaulnet/qauld:v2.0.0-beta.15
    restart: always
    user: 1000:1000
    ports:
      - 9229:9229
    volumes:
      - /home/user/containers/qaul/config:/srv/qaul
```
